In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.13.1
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    libraries = ['openblas', 'openblas']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE


In [3]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [4]:
np.full(10, 2.5)

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

In [5]:
!python3 -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
Z = np.zeros(10)
Z[4] = 1
Z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [7]:
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [52]:
np.arange(0,2, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8])

In [53]:
np.linspace(0, 2, 9)  # 9 чисел от 0 до 2 ВКЛЮЧИТЕЛЬНО

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [105]:
def f1(k,l):
    return k*k-l

f = np.fromfunction(f1, (3, 4))
f

array([[ 0., -1., -2., -3.],
       [ 1.,  0., -1., -2.],
       [ 4.,  3.,  2.,  1.]])

In [116]:
# поэлементное разворачивание массива в список
def gf():      # замудрил с генератором специально
    for i in f.flat:
        yield i

[g for g in gf()]

[0.0, -1.0, -2.0, -3.0, 1.0, 0.0, -1.0, -2.0, 4.0, 3.0, 2.0, 1.0]

In [9]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.nonzero([0,4,2,6,7,8,0,0])

(array([1, 2, 3, 4, 5]),)

In [11]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [12]:
np.random.random((3,3,3)) # Return random floats in the half-open interval [0.0, 1.0]

array([[[ 0.28428415,  0.50370166,  0.81746684],
        [ 0.66037795,  0.63240485,  0.34156461],
        [ 0.94559787,  0.77845843,  0.29451571]],

       [[ 0.60053674,  0.24517773,  0.92869341],
        [ 0.20523355,  0.04356575,  0.39748833],
        [ 0.98049606,  0.7758625 ,  0.47854384]],

       [[ 0.28238676,  0.28443464,  0.07066719],
        [ 0.50579878,  0.17776147,  0.04617154],
        [ 0.56999925,  0.3090867 ,  0.25235742]]])

In [98]:
p = np.random.randn(3,3,3) # Return a sample (or samples) from the "standard normal" distribution
p

array([[[ 0.85791239,  0.82361489,  1.69400263],
        [-1.26785961, -0.3715898 ,  0.59076588],
        [ 0.32710715, -0.79596714,  0.88160038]],

       [[ 0.63043129, -2.1439477 ,  0.39114102],
        [ 0.41481992,  1.52352573, -0.64538581],
        [ 1.48799805, -0.67910753, -1.51416723]],

       [[ 0.25012286, -0.75347932, -0.18525817],
        [-1.42890479, -0.55703226,  1.41253787],
        [ 0.28765713,  0.94431641, -0.8743568 ]]])

In [101]:
p[:2, ...]

array([[[ 0.85791239,  0.82361489,  1.69400263],
        [-1.26785961, -0.3715898 ,  0.59076588],
        [ 0.32710715, -0.79596714,  0.88160038]],

       [[ 0.63043129, -2.1439477 ,  0.39114102],
        [ 0.41481992,  1.52352573, -0.64538581],
        [ 1.48799805, -0.67910753, -1.51416723]]])

In [103]:
p[2, ... , 2] # непонятно что выводит

array([-0.18525817,  1.41253787, -0.8743568 ])

In [95]:
Z = np.random.random((5,5))
Z

array([[ 0.79165629,  0.23742892,  0.95501226,  0.79116896,  0.19908889],
       [ 0.53760114,  0.11864137,  0.17375739,  0.8665604 ,  0.47119162],
       [ 0.1855588 ,  0.45018048,  0.68910787,  0.87251418,  0.68363475],
       [ 0.97024611,  0.08156842,  0.90750775,  0.8928664 ,  0.22061872],
       [ 0.45769522,  0.544489  ,  0.18073384,  0.43153881,  0.36459841]])

In [15]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0812311467244 0.938021645056


In [97]:
Z.shape

(5, 5)

In [16]:
v = np.random.random(30)
v

array([ 0.70979802,  0.08072829,  0.7973902 ,  0.549428  ,  0.09966073,
        0.40075834,  0.57627681,  0.84349358,  0.02592168,  0.55667982,
        0.82927712,  0.38035322,  0.53436687,  0.41026034,  0.81873937,
        0.92652869,  0.22660788,  0.59563655,  0.12518248,  0.79463589,
        0.55591663,  0.18524304,  0.59047777,  0.75827772,  0.2687448 ,
        0.83756081,  0.20873078,  0.17268123,  0.007033  ,  0.19959719])

In [17]:
v.mean()

0.46886622791921106

In [18]:
m = np.ones((10,10))
m

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [19]:
m[1:-1, 1:-1] = 0
m

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [20]:
0*np.nan

nan

In [21]:
np.nan == np.nan

False

In [22]:
np.inf > np.nan

False

In [23]:
np.nan - np.nan

nan

In [24]:
0.3 == 3 * 0.1

False

In [25]:
3 * 0.1

0.30000000000000004

In [26]:
np.diag(np.arange(1,6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [27]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [28]:
z = np.zeros((8,8), dtype='int')
z[::2,::2] = z[1::2,1::2] = 1
z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [29]:
np.unravel_index(100, (6,7,8)) # Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

(1, 5, 4)

In [3]:
np.tile(np.array([[0,1], [1,0]]), (4,4)) # np.tile([[0,1], [1,0]], (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [31]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [32]:
z = np.arange(10) # Дан массив, поменять знак у элементов, значения которых между 3 и 8
z[(z > 3) & (z < 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

In [38]:
np.random.randint(0,4, (5,5)) # Матрица 5х5 с рандомными значениями

array([[3, 3, 1, 3, 0],
       [0, 0, 2, 1, 0],
       [0, 0, 1, 1, 3],
       [2, 0, 3, 0, 1],
       [3, 1, 2, 2, 2]])

In [63]:
z = np.zeros((5,5)) # Создать 5x5 матрицу со значениями в строках от 0 до 4
z += np.arange(5)
print(z)
np.tile(np.arange(0,5), (5,1))

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [68]:
def gen():
    for i in range(10):
        yield i
        
np.fromiter(gen(), np.float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [69]:
# Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое
np.linspace(0,1,12)[1:-1]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

In [74]:
a = np.sort(np.random.random(10)) # a.sort()
a

array([ 0.03747175,  0.17469795,  0.23599481,  0.41951641,  0.48766858,
        0.80931326,  0.85788783,  0.87680375,  0.90101964,  0.90199229])

In [76]:
a.round()

array([ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.])

In [81]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
np.allclose(a,b)
# np.allclose()

False

In [84]:
z = np.zeros(10)
print(z.flags)
z.flags.writeable = False
z[0] = 1

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


ValueError: assignment destination is read-only

In [89]:
# Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную
z = np.random.random((10,2))
x, y = z[:,0], z[:,1]
R = np.hypot(x,y)
T = np.arctan2(x,y)
print(x, y, sep='\n')

[ 0.71246364  0.55323693  0.50179342  0.48676461  0.05347803  0.69154494
  0.41566396  0.56871341  0.92809463  0.09014894]
[ 0.35227392  0.36344911  0.56479473  0.74058684  0.02536132  0.485256
  0.8684817   0.4850107   0.71549212  0.73051038]


In [92]:
Z = np.random.random(10) # Заменить максимум на 0
Z[Z.argmax()] = 0        # argmax возвращает индекс максимального элемента
Z

array([ 0.66813162,  0.07283311,  0.09928054,  0.61959224,  0.        ,
        0.27934381,  0.37684718,  0.0115703 ,  0.33695681,  0.01809643])

??????????????????????????????????????????????????????????????????????

Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [ ]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

??????????????????????????????????????????????????????????????????????????

In [8]:
np.set_printoptions(threshold=np.nan) # вроде по-умолчанию включено
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
np.random.uniform(0,10,10)

array([ 6.16794984,  8.96246148,  8.1626831 ,  1.07960966,  5.32140767,
        9.25713963,  7.74824272,  4.10845857,  5.56934293,  6.21507455])

Найти ближайшее к заданному значению число в заданном массиве

In [15]:
Z = np.arange(100) # создаем массив
v = np.random.uniform(0,100) # создали число.
# равномерное распределение. Зачем оно тут?
index = (np.abs(Z-v)).argmin() # создаем массив абсолютных значений 
# разницы каждого элемента массива и нашего числа
# и берем индекс минимума 
# выводим
Z[index]

28

In [27]:
z = np.zeros(1,  [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
z

array([(( 0.,  0.), ( 0.,  0.,  0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [32]:
import scipy as sp

z = np.random.random((10,2))
dist = scipy.spatial.distance.cdist(z,z)
dist

array([[ 0.        ,  0.34573692,  0.8678823 ,  0.48252622,  0.6783819 ,
         0.55584128,  0.53216827,  0.73672211,  0.7861982 ,  0.74408189],
       [ 0.34573692,  0.        ,  0.5733073 ,  0.18814271,  0.5094139 ,
         0.41083375,  0.28911448,  0.39679049,  0.44887854,  0.44946946],
       [ 0.8678823 ,  0.5733073 ,  0.        ,  0.61242294,  0.9207109 ,
         0.4135393 ,  0.710019  ,  0.46816545,  0.49637415,  0.67344732],
       [ 0.48252622,  0.18814271,  0.61242294,  0.        ,  0.3450534 ,
         0.56651721,  0.11426337,  0.27668047,  0.31765057,  0.26777757],
       [ 0.6783819 ,  0.5094139 ,  0.9207109 ,  0.3450534 ,  0.        ,
         0.90967463,  0.23080662,  0.47860264,  0.48086275,  0.29388868],
       [ 0.55584128,  0.41083375,  0.4135393 ,  0.56651721,  0.90967463,
         0.        ,  0.68010696,  0.61967397,  0.67169752,  0.77183723],
       [ 0.53216827,  0.28911448,  0.710019  ,  0.11426337,  0.23080662,
         0.68010696,  0.        ,  0.31593594

Преобразовать массив из float в int

In [34]:
z = np.arange(5, dtype=np.int32)
z = z.astype(np.float32, copy=False)
z

array([ 0.,  1.,  2.,  3.,  4.], dtype=float32)

```
1,2,3,4,5
6,,,7,8
,,9,10,11
```

In [38]:
t = np.genfromtxt('file.txt', delimiter=',')
t

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,  nan,  nan,   7.,   8.],
       [ nan,  nan,   9.,  10.,  11.]])

enumerate

In [41]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print()
# МАГИЯ какая-то
for index in np.ndindex(Z.shape): 
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [43]:
t.reshape((5,3))

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [ nan,  nan,   7.],
       [  8.,  nan,  nan],
       [  9.,  10.,  11.]])

In [47]:
t

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,  nan,  nan,   7.,   8.],
       [ nan,  nan,   9.,  10.,  11.]])

In [46]:
np.hsplit(t, 5)

[array([[  1.],
        [  6.],
        [ nan]]), array([[  2.],
        [ nan],
        [ nan]]), array([[  3.],
        [ nan],
        [  9.]]), array([[  4.],
        [  7.],
        [ 10.]]), array([[  5.],
        [  8.],
        [ 11.]])]