In [66]:
import numpy as np

### Reshaping

In [4]:
a = np.random.randint(0,50, (5,4))
a

array([[40, 19,  7,  4],
       [ 7,  7,  2,  8],
       [11,  8,  1,  6],
       [29, 32, 33, 45],
       [23,  8, 20, 11]])

In [5]:
a.shape

(5, 4)

In [6]:
a.ravel()

array([40, 19,  7,  4,  7,  7,  2,  8, 11,  8,  1,  6, 29, 32, 33, 45, 23,
        8, 20, 11])

In [7]:
a.shape = (2,10)
a

array([[40, 19,  7,  4,  7,  7,  2,  8, 11,  8],
       [ 1,  6, 29, 32, 33, 45, 23,  8, 20, 11]])

In [8]:
a.T

array([[40,  1],
       [19,  6],
       [ 7, 29],
       [ 4, 32],
       [ 7, 33],
       [ 7, 45],
       [ 2, 23],
       [ 8,  8],
       [11, 20],
       [ 8, 11]])

In [9]:
a.reshape((5,4))

array([[40, 19,  7,  4],
       [ 7,  7,  2,  8],
       [11,  8,  1,  6],
       [29, 32, 33, 45],
       [23,  8, 20, 11]])

In [10]:
a.reshape((2,-1)) # Если указан -1, то второе значение расчитывается в зав-ти от количества значений

array([[40, 19,  7,  4,  7,  7,  2,  8, 11,  8],
       [ 1,  6, 29, 32, 33, 45, 23,  8, 20, 11]])

In [11]:
a.resize((5,4)) # результат операции сохраняется
a

array([[40, 19,  7,  4],
       [ 7,  7,  2,  8],
       [11,  8,  1,  6],
       [29, 32, 33, 45],
       [23,  8, 20, 11]])

### Merging

In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [13]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [15]:
np.column_stack((a,b)) # 1-D arrays merge into columns of 2-D array

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [16]:
np.row_stack((a,b)) # 1-D arrays merge into rows of 2-D array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Splitting

In [17]:
a = np.arange(12).reshape((2,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [18]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

In [19]:
np.hsplit(a, 2)

[array([[0, 1, 2],
        [6, 7, 8]]), array([[ 3,  4,  5],
        [ 9, 10, 11]])]

In [20]:
np.hsplit(a, (2,))

[array([[0, 1],
        [6, 7]]), array([[ 2,  3,  4,  5],
        [ 8,  9, 10, 11]])]

In [21]:
np.hsplit(a, (1,3))

[array([[0],
        [6]]), array([[1, 2],
        [7, 8]]), array([[ 3,  4,  5],
        [ 9, 10, 11]])]

### Copies and views

In [22]:
b = a

In [23]:
b is a

True

In [24]:
b.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [26]:
b.shape = (3,4)

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
c = a.view() # Создает новый массив представляющий те же данные

In [29]:
c is a

False

In [30]:
c.base

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
c.base is a

False

In [32]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
c.shape = (2,6) # изменит форму только с, как представления

In [34]:
c[1,3] = 345 # изменит значение в а

In [35]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8, 345,  10,  11]])

In [36]:
c

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8, 345,  10,  11]])

#### Slice is a view

In [37]:
s = a[:,2:3]

In [38]:
s[:] = 10

In [39]:
a

array([[  0,   1,  10,   3],
       [  4,   5,  10,   7],
       [  8, 345,  10,  11]])

### Deep copy

In [40]:
d = a.copy()

In [41]:
d[...] = 30

In [42]:
d

array([[30, 30, 30, 30],
       [30, 30, 30, 30],
       [30, 30, 30, 30]])

In [43]:
a

array([[  0,   1,  10,   3],
       [  4,   5,  10,   7],
       [  8, 345,  10,  11]])

### Random

In [46]:
np.random.sample()

0.11431326693063237

In [49]:
np.random.sample((2,3))

array([[ 0.60728243,  0.66674623,  0.71790702],
       [ 0.67822198,  0.23346742,  0.05090829]])

In [52]:
np.random.randint(0,3,10) # Не включает 3 в список

array([2, 1, 0, 2, 1, 0, 1, 2, 1, 1])

In [53]:
np.random.random_integers(0,3,10) # Включает 3 в список 

/home/ska/virtenv/bigd/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 3 + 1) instead
  """Entry point for launching an IPython kernel.


array([1, 3, 1, 2, 3, 1, 0, 0, 0, 2])

In [54]:
np.random.randint(0,3+1,10)

array([0, 1, 0, 3, 2, 0, 2, 1, 2, 0])

In [65]:
np.random.uniform(2, 8, (2,5))         #Равномерное (uniform) распределение

array([[ 6.82794858,  6.75673731,  6.57579128,  7.04429019,  4.97415633],
       [ 3.76822825,  7.54944809,  4.06320466,  4.20970734,  4.3650404 ]])

### Shuffle

In [68]:
a = np.arange(10)
np.random.shuffle(a)
a

array([2, 1, 6, 3, 0, 5, 7, 8, 9, 4])

In [69]:
np.random.permutation(10)

array([2, 6, 3, 4, 1, 7, 5, 9, 0, 8])

In [73]:
np.random.choice(10, (3,3), replace=False) # replace одно число может выбираться повторно

array([[4, 9, 8],
       [2, 3, 0],
       [1, 7, 5]])

### Generator seed

In [82]:
np.random.seed(10)
np.random.random(5)

array([ 0.77132064,  0.02075195,  0.63364823,  0.74880388,  0.49850701])

In [83]:
np.random.random(5)

array([ 0.22479665,  0.19806286,  0.76053071,  0.16911084,  0.08833981])

In [84]:
np.random.seed(10) # инициализирует генератор с определенным состоянием
np.random.random(5) # результат аналогичен результату выше

array([ 0.77132064,  0.02075195,  0.63364823,  0.74880388,  0.49850701])

In [86]:
state = np.random.get_state()

In [87]:
np.random.random(5)

array([ 0.22479665,  0.19806286,  0.76053071,  0.16911084,  0.08833981])

In [89]:
np.random.set_state(state)
np.random.random(5)

array([ 0.22479665,  0.19806286,  0.76053071,  0.16911084,  0.08833981])

### np.linalg

#### Возведение в степень
linalg.matrix_power(M, n) - возводит матрицу в степень n.

#### Разложения
linalg.cholesky(a) - разложение Холецкого.

linalg.qr(a[, mode]) - QR разложение.

linalg.svd(a[, full_matrices, compute_uv]) - сингулярное разложение.

#### Некоторые характеристики матриц
linalg.eig(a) - собственные значения и собственные векторы.

linalg.norm(x[, ord, axis]) - норма вектора или оператора.

linalg.cond(x[, p]) - число обусловленности.

linalg.det(a) - определитель.

linalg.slogdet(a) - знак и логарифм определителя (для избежания переполнения, если сам определитель очень маленький).

#### Системы уравнений
linalg.solve(a, b) - решает систему линейных уравнений Ax = b.

linalg.tensorsolve(a, b[, axes]) - решает тензорную систему линейных уравнений Ax = b.

linalg.lstsq(a, b[, rcond]) - метод наименьших квадратов.

linalg.inv(a) - обратная матрица.

[описание на сайте SciPy](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html 'docs.scipy.org')